spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: create

    datasource:
        url: jdbc:mysql://mysql:3306/qacinemas
        username: user
        password: pass
        driver-class-name: com.mysql.jdbc.Driver